#if !canImport(ObjectiveC)
import XCTest

extension AdderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AdderTests = [
        ("test_AddingOneAndOneIsTwo", test_AddingOneAndOneIsTwo),
        ("test_AddingOneAndZeroIsOne", test_AddingOneAndZeroIsOne),
        ("test_AddingZeroAndOneIsOne", test_AddingZeroAndOneIsOne),
        ("test_AddingZeroAndZeroIsZero", test_AddingZeroAndZeroIsZero),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AdderTests.__allTests__AdderTests),
    ]
}
#endif
